[workspace]
name = "performance-minicourse"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[dependencies]
python = ">=3.12"
numpy = ">=2"
matplotlib = ">=3.10"
pandas = ">=2"
scipy = ">=1.8"
jupyterlab = ">=3"
plumbum = ">=1.10"
numba = ">=0.60"
numexpr = ">=2.8"
jax = ">=0.3"
dask = "*"
distributed = "*"
line_profiler = "*"
ipywidgets = "*"
ipympl = "*"
python-graphviz = "*"
nb_conda_kernels = "*"
jupyterlab_code_formatter = "*"
black = "*"
isort = "*"
rich = "*"

[tasks]
lab = "jupyter lab"
