[workspace]
name = "performance-minicourse"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[dependencies]
dask = "*"
distributed = "*"
ipympl = "*"
ipywidgets = "*"
jax = ">=0.3"
jupyterlab = ">=3"
line_profiler = "*"
matplotlib = ">=3.10"
numba = ">=0.60"
numexpr = ">=2.8"
numpy = ">=2"
pandas = ">=2"
plumbum = ">=1.10"
pytest = "*"
python = ">=3.12"
python-graphviz = "*"
rich = "*"
scipy = ">=1.8"

[tasks]
lab = "jupyter lab"
